// GENERATED by aura-engine/sync.mjs: do not edit here, edit /home/claude/aura-engine and re-run sync.
// Aura engine — situation / relation / sign detection for free text (IT + EN).
// Pure ESM, no dependencies: runs in Node and in the browser.

export const SITUATIONS = [
  'fight', 'jealousy_control', 'silence_ghosting', 'coldness_distance', 'ex_back', 'breakup',
  'betrayal', 'apology', 'first_move', 'new_relationship', 'commitment_future', 'cohabitation',
  'money', 'family_boundaries', 'parent_child', 'friendship_rift', 'work_conflict', 'asking_need',
  'hard_feedback', 'support_hard_time', 'neglect_attention', 'affection_closeness',
  'disagreement_decision', 'reconnect'
];

export const SIGN_IDS = [
  'aries', 'taurus', 'gemini', 'cancer', 'leo', 'virgo',
  'libra', 'scorpio', 'sagittarius', 'capricorn', 'aquarius', 'pisces'
];

export const SIGN_NAMES = {
  it: {
    aries: 'Ariete', taurus: 'Toro', gemini: 'Gemelli', cancer: 'Cancro', leo: 'Leone', virgo: 'Vergine',
    libra: 'Bilancia', scorpio: 'Scorpione', sagittarius: 'Sagittario', capricorn: 'Capricorno',
    aquarius: 'Acquario', pisces: 'Pesci'
  },
  en: {
    aries: 'Aries', taurus: 'Taurus', gemini: 'Gemini', cancer: 'Cancer', leo: 'Leo', virgo: 'Virgo',
    libra: 'Libra', scorpio: 'Scorpio', sagittarius: 'Sagittarius', capricorn: 'Capricorn',
    aquarius: 'Aquarius', pisces: 'Pisces'
  }
};

// Tie-break order (earlier wins on equal score).
const PRIORITY = [
  'betrayal', 'breakup', 'ex_back', 'jealousy_control', 'support_hard_time', 'silence_ghosting',
  'apology', 'family_boundaries', 'parent_child', 'work_conflict', 'money', 'cohabitation',
  'commitment_future', 'first_move', 'new_relationship', 'reconnect', 'friendship_rift',
  'neglect_attention', 'affection_closeness', 'coldness_distance', 'hard_feedback',
  'disagreement_decision', 'fight', 'asking_need'
];
const TIERS = [
  ['betrayal', 'breakup', 'ex_back', 'jealousy_control', 'support_hard_time', 'apology', 'first_move',
    'new_relationship', 'commitment_future', 'cohabitation', 'money', 'family_boundaries',
    'affection_closeness', 'reconnect', 'neglect_attention', 'silence_ghosting'],
  ['asking_need', 'hard_feedback'],
  ['friendship_rift', 'parent_child', 'work_conflict'],
  ['fight', 'coldness_distance', 'disagreement_decision']
];
const RANK = Object.fromEntries(PRIORITY.map((s, i) => [s, i]));

// ---------------------------------------------------------------------------
// Normalisation
// ---------------------------------------------------------------------------
const SHORTHAND = [
  [/\bnn\b/g, 'non'], [/\b(xke|xche|perke|xk)\b/g, 'perche'], [/\bcmq\b/g, 'comunque'],
  [/\bke\b/g, 'che'], [/\bx\b/g, 'per'], [/\bqlc\w*\b/g, 'qualcosa'], [/\bmsg\b/g, 'messaggio'],
  [/\bbf\b/g, 'boyfriend'], [/\bgf\b/g, 'girlfriend'], [/\bu\b/g, 'you'], [/\bur\b/g, 'your'],
  [/\bim\b/g, "i'm"], [/\bive\b/g, "i've"], [/\bdont\b/g, "don't"], [/\bdoesnt\b/g, "doesn't"],
  [/\bdidnt\b/g, "didn't"], [/\bcant\b/g, "can't"], [/\bwont\b/g, "won't"], [/\bisnt\b/g, "isn't"],
  [/\bhasnt\b/g, "hasn't"], [/\bhavent\b/g, "haven't"], [/\bwasnt\b/g, "wasn't"], [/\bhes\b/g, "he's"],
  [/\bshes\b/g, "she's"], [/\btheyre\b/g, "they're"], [/\bthx\b/g, 'thanks'], [/\bpls\b/g, 'please'],
  [/\bmum\b/g, 'mom'], [/\bmommy\b/g, 'mom'], [/\bgonna\b/g, 'going to'], [/\bwanna\b/g, 'want to'],
  [/\bsmth\b/g, 'something'], [/\bppl\b/g, 'people'], [/\bdm'?d\b/g, 'messaged'], [/\btxt\b/g, 'text']
];

export function normalize(text) {
  let s = String(text || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
  s = s.replace(/[’‘`´]/g, "'").replace(/[“”«»]/g, '"');
  s = s.replace(/([a-z])\1{2,}/g, '$1'); // "noooo" -> "no", "sooo" -> "so"
  for (const [re, rep] of SHORTHAND) s = s.replace(re, rep);
  return s.replace(/\s+/g, ' ').trim();
}

// ---------------------------------------------------------------------------
// Lexicon: [weight, regex source] — sources are wrapped in word boundaries.
// A leading "!" marks a pattern that is ignored when negated ("non sono geloso").
// ---------------------------------------------------------------------------
const HIM = '(?:him|her|them)';
const HIS = '(?:his|her|their)';
const DAYS_SHORT = '(?:ieri|stamattina|stamani|oggi|ore|\\d+ ?ore|(?:un|uno|due|tre|quattro|cinque|\\d+|qualche|pochi|alcuni) giorn[oi]|una settimana|giorni)';
const TIME_LONG = '(?:mesi|anni|un anno|tanto tempo|molto tempo|una vita|secoli|tantissimo)';

const LEX = {
  fight: [
    [3, 'got into it|it got (?:really |so |pretty )?(?:nasty|ugly|heated|bad)'],
    [2, "casino con|mi ha dato (?:del|della|dello)|(?:ho|mi ha|gli ho|le ho) rispost\\w* male|mi ha trattat\\w* male|(?:e|se n'e) (?:uscit|andat)\\w* sbattendo|abbiamo avuto da dire|scenata"],
    [2.5, '\\brow\\b|stormed (?:out|off)|blew up at|hung up on me|screamed at|went off on me|called me (?:crazy|names)'],
    [3, 'abbiamo (?:litigato|discusso|avuto una discussione)'], [3, 'ci siamo (?:urlat\\w*|detti cose|scontrat\\w*|mandat\\w* a quel paese)'],
    [2.5, 'litig\\w*|littig\\w*|lite|liti'], [2, 'discussione|discusso|scazz\\w*|sclerat\\w*|sclero'],
    [1.5, 'urlat\\w*|urla(?:to|va|re)?|gridat\\w*|sbattut\\w* la porta|mi ha attaccat\\w*|mi ha aggredit\\w*'],
    [1, '!incazzat\\w*|!arrabbiat\\w*|!furios\\w*|nervos\\w*|tensione|teso|tesa|offes\\w*|se l\'e presa|si e offes\\w*'],
    [3, '(?:we|i) (?:had|got into) (?:a|an|this|our|another) (?:\\w+ )?(?:fight|argument|row|blowup|blow-up)'],
    [2.5, 'fight|fought|argument|argued|arguing|blew up|blow-up|blowup|screaming match'],
    [1.5, 'yell\\w*|shout\\w*|scream\\w* at|snapped at|slammed the door|said hurtful things|lost my temper|lost it'],
    [1, '!angry|!mad at|!pissed|heated|tense|upset with me']
  ],
  jealousy_control: [
    [2.5, 'checks? (?:who|what|where) i|asks? about every (?:girl|guy|person)|chi seguo|mi chiede di ogni|vuole la mia password|wants my passwords?|my password'],
    [3, '(?:gets|get|got) (?:upset|angry|mad|jealous) (?:when|if|whenever) i (?:talk|text|go|see|hang)|male friends|female friends|amici maschi|amiche femmine|si arrabbia (?:se|quando) (?:parlo|esco|scrivo|vedo)|chi (?:la|le) guarda|chi guarda le mie storie'],
    [3, "terzo grado|interrogatori\\w*|non posso (?:uscire|vedere|parlare) (?:con|senza)|mi fa pesare (?:ogni|quando esco)|wants? my location|location 24/7|freaks? out (?:if|when|whenever) i|can't (?:go out|see my friends|hang out)|interrogat\\w*"],
    [3, '!gelos\\w*|!geloz\\w*|!gelosia'], [3, 'mi controll\\w*|controll\\w* (?:il|i) (?:mio|miei) (?:telefono|cellulare|messaggi)|guarda (?:il mio|nel mio) (?:telefono|cellulare)|legge i miei messaggi'],
    [3, 'possessiv\\w*|mi fa (?:le )?scenate|non vuole che (?:esca|veda|vada|parli)|vuole sapere (?:sempre )?dove sono|con chi (?:esco|sono|parlo|scrivo)|mi chiede (?:sempre )?dove sono'],
    [3, '(?:sua|suo) ex|la ex di (?:lui|lei)|(?:scrive|chatta|parla) (?:ancora )?con (?:la|il) (?:sua|suo) ex'],
    [2.5, '!sospett\\w*|mi sento insicur\\w*|like (?:a|alle foto di) (?:un\'altra|un altro|altre|altri)|mette like|ha messo like|segue (?:un\'altra|altre ragazze)|chatta con (?:un\'altra|un altro|una collega)|posizione (?:condivisa|in tempo reale)'],
    [2, 'controllo|controllare|controllarmi|gelos'],
    [3, '!jealous\\w*|!jealousy|controlling|possessive|checks my phone|(?:goes|went|going) through my phone|reads my (?:texts|messages)|tracks my location|shares? (?:my|our) location'],
    [3, "(?:his|her|their) ex\\b|(?:texting|talking to|messaging|follows) (?:his|her|their) ex|doesn't want me to (?:go out|see|hang out|talk)|wants to know where i am|who i'm (?:with|texting|talking to)"],
    [2.5, '!suspicious|insecure|liked (?:a|another|some) (?:girl|guy|woman|man)|(?:flirting|flirts) with|likes other (?:girls|guys)'],
    [1.5, 'control\\w*|accus\\w* me of']
  ],
  silence_ghosting: [
    [2.5, "non mi (?:scrive|cerca|chiama|risponde)(?: niente| nulla| mai)?|non (?:scrive|risponde) (?:piu|niente|nulla)|neanche un (?:messaggio|buongiorno|ciao)|(?:giorni|ore|settimana) (?:che|senza) (?:non )?(?:mi )?(?:scrive|sentirl\\w*|risposta)|doesn't text (?:me )?(?:back|anymore)|won't text|no texts?|stopped (?:talking|writing)|not a single (?:text|message)"],
    [3, "zero messaggi|nessun messaggio|non si e piu fatt\\w* viv\\w*|non si fa viv\\w*|(?:still|never) (?:hasn't|haven't|didn't)? ?(?:texted|replied|written) (?:me )?back|hasn't texted (?:me )?back"],
    [3, 'visualizza e non rispond\\w*|mi ha visualizzat\\w*|lascia(?:to)? (?:in )?visualizzat\\w*|spunte blu|doppia spunta|ghostat\\w*|ghosting|mi ha ghost\\w*|gost\\w*'],
    [3, 'non (?:mi )?(?:ha )?(?:piu )?(?:rispost\\w*|rispond\\w*|risponde)|non (?:mi )?risponde (?:piu|al telefono|ai messaggi)|nessuna risposta|zero risposte'],
    [3, `non (?:si fa|si e fatt\\w*) (?:piu )?sentire|non mi (?:scrive|cerca|chiama) (?:piu|da)|non (?:lo|la|li) sento da ${DAYS_SHORT}|sparit\\w*|scompars\\w* nel nulla|scompars\\w*|mi ignora|mi sta ignorando|mi ha bloccat\\w*|bloccat\\w*`],
    [2, `silenzio|da ${DAYS_SHORT}|non mi (?:ha )?richiamat\\w*|visualizzat\\w*|ignorat\\w*|muto|muta`],
    [3, "ghost\\w*|left me on (?:read|delivered)|(?:leaves|leaving|left) me on read|on read|read receipts?|silent treatment|radio silence|went (?:silent|quiet|mia|awol|dark)"],
    [3, "(?:isn't|not|hasn't|won't|stopped|doesn't|never) (?:been )?(?:replying|responding|answering|texting (?:me )?back|reply(?:ing)?|respond(?:ing)?|answer(?:ing)?|text(?:ed|ing)? (?:me )?back)|haven't heard (?:back|from)|(?:hasn't|didn't) (?:replied|texted|called|messaged)|no (?:reply|response|answer)"],
    [2.5, 'ignor(?:ing|es|ed) me|disappeared|vanished|blocked me|unfollowed me|seen (?:it|my message) and|saw (?:it|my message) and (?:didn\'t|never)'],
    [1.5, 'silence|quiet|(?:two|three|\\d+|a few|couple of) days']
  ],
  coldness_distance: [
    [2.5, 'used to (?:text|call|message) me|(?:barely|hardly) (?:texts?|talks?|anything|replies|responds)|no (?:more )?emojis|prima (?:mi )?scriveva|scriveva sempre|non (?:mi )?scrive piu come|sempre meno|less and less|niente cuori'],
    [3, '(?:just|only) (?:ok|k|fine|yes|no)\\b|solo (?:ok|si|va bene)\\b'],
    [3, 'not as (?:warm|affectionate|sweet|present) as (?:before|usual)|talking to a wall|parlare con un muro|(?:la|lo) sento lontan[oa]|lontan[oa] ultimamente|sembra lontan[oa]'],
    [3, 'risposte secche|risponde a monosillabi|monosillab\\w*|risponde (?:solo )?(?:ok|si|boh|bene)\\b|e cambiat\\w*|non e piu (?:lo stesso|la stessa|come prima)|sulle sue|freddezza|(?:piu|molto|super|cosi) (?:freddo|fredda|distante|distaccat\\w*)'],
    [2.5, 'freddo|fredda|freddi|freddino|freddina|distant[ei]|distaccat\\w*|assente|meno presente|diverso ultimamente|chius\\w* in se stess\\w*|si e chius\\w*|si sta allontanando|allontanat\\w*'],
    [1, 'distanza|secco|secca|strano ultimamente|strana ultimamente'],
    [3, "(?:pulling|pulled|pulls) away|one[- ]word (?:answers|replies|texts)|dry (?:texts|replies|texting)|short replies|(?:so|really|super|more) (?:cold|distant)|not the same (?:person|anymore)|checked out|lost interest|losing interest|(?:acting|been) (?:off|weird|different|distant|cold)"],
    [2.5, 'cold|colder|distant|withdrawn|aloof|lukewarm|less interested|less present|changed lately|shut(?:s|ting)? down|closed off'],
    [1, 'distance|weird lately|off lately']
  ],
  ex_back: [
    [3, 'win back|get back my ex|riprendermi (?:il mio|la mia) ex|tornare con (?:il mio|la mia) ex'],
    [3, '(?:la mia|il mio|mia|mio|una mia|un mio) ex\\b|ex (?:ragazz[oa]|fidanzat[oa]|compagn[oa]|marito|moglie)|l\'ex\\b|all\'ex\\b|dell\'ex\\b|riconquist\\w*|tornare insieme|rimetterci insieme|tornare con (?:lui|lei)|ritornare con|riprenderl[ao]|riaverl[ao]'],
    [2, 'seconda possibilita|riprovarci|ci siamo lasciati|mi manca (?:lui|lei|da morire|tanto|troppo)'],
    [2, `(?:lasciat\\w*|mollat\\w*) (?:da )?${TIME_LONG}|(?:${TIME_LONG}|settimane) fa (?:ci siamo lasciati|mi ha lasciat\\w*)`],
    [3, "my ex\\b|ex[- ]?(?:boyfriend|girlfriend|husband|wife|partner|bf|gf)\\b|(?:get|win|want) (?:him|her|them) back|back together|get back with|getting back with|second chance|since we broke up|after (?:the|our) break ?up"],
    [2, '(?:broke up|split up|split) (?:\\w+ )?(?:months|years|weeks|a year|a month) ago|miss (?:him|her|them) (?:so much|a lot|like crazy)|i still (?:love|miss)']
  ],
  breakup: [
    [3, 'voglio lasciarl\\w*|(?:vorrei|devo|dovrei|penso di|sto pensando di|non so se|come) lasciarl\\w*|lasciarl[aoi](?! (?:stare|perdere|in pace|andare|fare|spazio|tempo|sol))|lasciarti|voglio lasciare (?:il mio|la mia|mio|mia)'],
    [3, 'chiudere (?:la relazione|la storia|con (?:lui|lei)|tutto|questa storia)|mi ha lasciat[oa]|mi ha mollat[oa]|mollarl[aoi]|rompere con|e finita|finire (?:la|questa) (?:storia|relazione)|non (?:lo|la|ti) amo piu|non sono piu innamorat\\w*|pausa di riflessione|prenderci una pausa|separar\\w*|separazione|divorzi\\w*'],
    [1.5, 'ci siamo lasciati|lasciarsi|lasciare (?:il mio|la mia|mio|mia)|finita'],
    [3, "break up|breaking up|broke up with me|dumped me|dump (?:him|her|them)|leave (?:him|her|them|my (?:husband|wife|boyfriend|girlfriend|partner))|leaving (?:him|her|them|my)|end (?:it|things|the relationship|our relationship)|ending (?:it|things)|call it quits|not in love (?:with (?:him|her|them) )?anymore|fell out of love|want a divorce|divorce|separat\\w*|take a break|on a break"],
    [1.5, 'broke up|split up|breakup|it\'s over']
  ],
  betrayal: [
    [3, 'segret[oa]|chat segret\\w*|di nascosto|secret(?:ly)?|hidden (?:chat|account|profile)'],
    [3, 'mi ha nascost\\w*|mi nascondeva|(?:found|saw) (?:tinder|hinge|bumble|a dating app|dating apps) on (?:his|her|their) phone|hid (?:it|this|that) from me|hiding (?:something|things) from me'],
    [3, "texting (?:another|other|some) (?:woman|man|girl|guy|women|men|girls|guys)|behind my back|alle mie spalle|messaggi con (?:un'altra|un altro)|flirt\\w* (?:with )?behind"],
    [4, '!tradit[oa]|!tradisce|!tradiva|tradimento|mi ha tradit\\w*|mi tradisce|mi tradiva|trad+it\\w*|corna|cornificat\\w*|amante|doppia vita|ha un\'altra|ha un altro|si vede(?:va)? con (?:un\'altra|un altro|una|la sua ex)|ci e andat[oa] a letto|e andat[oa] a letto con'],
    [3, 'mi ha mentit\\w*|mi ha detto una bugia|mi ha raccontato (?:un sacco di )?bugie|mentit\\w*|bugi[ae]|ho scoperto che|l\'ho scopert\\w*|ho trovato (?:dei|i|messaggi|delle)|fiducia (?:rotta|tradita|persa|distrutta)|non mi fido piu|mi ha preso in giro'],
    [4, "cheated on me|(?:is|been|was) cheating|cheating on me"], [3, "!cheat\\w*|affair|unfaithful|slept with|hooked up with|sexting|secret (?:account|profile|tinder)|seeing someone else|another (?:woman|man|girl|guy) (?:on|in) (?:his|her|their) phone"],
    [3, "lied to me|lying to me|(?:he|she|they) lied|caught (?:him|her|them)|found out (?:that|about|he|she|they)|betray\\w*|broke my trust|can't trust (?:him|her|them)|trust is (?:gone|broken)|lies"]
  ],
  apology: [
    [3, '!apolog\\w*|owe (?:him|her|them) an apology|chiedere perdono|devo delle scuse|gli devo delle scuse|le devo delle scuse'],
    [3, 'mi scuso|come (?:mi )?scus\\w*|scusarmi'],
    [2.5, 'mi sento (?:una merda|uno schifo|in colpa|malissimo per)|i feel (?:terrible|awful|so bad|guilty)|sense of guilt'],
    [3, '(?:ho|avevo) sbagliat\\w*|(?:e stata )?colpa mia'], [3, 'chied\\w* scusa|scusarmi|mi voglio scusare|farmi perdonare|ho esagerat\\w*|ho fatto una cazzata|ho fatto un casino|ho detto cose che non pensavo|mi sono comportat\\w* (?:male|da stronz\\w*)|ho ferit\\w*|(?:l|la|lo)\'ho ferit\\w*|mi sono pentit\\w*|sono pentit\\w*|rimediare'],
    [1.5, 'perdon\\w*|scusa|scuse|cazzata|mi dispiace'],
    [3, "(?:it was|it's|totally|all) my fault|i was wrong"], [3, "!apologi[sz]\\w*"], [3, "say (?:i'm |that i'm )?sorry|saying sorry|i messed up|i screwed up|i f\\w*ed up|i was wrong|i overreacted|make it up to|i hurt (?:him|her|them)|i shouldn't have|i regret (?:what|saying|it)|made a (?:huge |big )?mistake|forgive me|i was a jerk"],
    [1.5, 'sorry|my bad|regret']
  ],
  first_move: [
    [2.5, "(?:che )?mi interessa|far(?:gli|le)? capire che mi (?:piace|interessa)|let (?:him|her|them) know i(?:'m)? (?:like|into|interested)|i like (?:him|her)|mi piace (?:lui|lei)|interessat[oa] a (?:lui|lei)"],
    [3, 'feelings for (?:him|her|them|my|a)|have feelings|provo qualcosa per|ho (?:dei )?sentimenti per|scrivere a (?:una|un) (?:ragazz\\w*|tipo|tipa) conosciut\\w*'],
    [3, "cute (?:guy|girl|boy)|ask (?:for )?(?:his|her|their) number|get (?:his|her|their) number|there's this (?:guy|girl)|there is this (?:cute )?(?:guy|girl)|chieder\\w* il numero|c'e (?:un|una) (?:ragazz\\w*|tipo|tipa) che mi piace|che mi piace, come"],
    [3, 'ho (?:una|preso una|presa una) cotta|mi sono pres[oa] una cotta|cotta per|mi piace (?:un|una|un\'|questo|questa|tanto|molto|da morire|parecchio) ?(?:ragazz\\w*|tipo|tipa|collega|amic\\w*|persona|compagn\\w*|lui|lei)?|mi piace (?:lui|lei)'], [3, 'dichiar\\w*|chieder\\w* di uscire|invitar\\w* (?:a uscire|fuori|a prendere)|fare il primo passo|primo passo|farmi avanti|primo messaggio|scrivergli per la prima volta|scriverle per la prima volta|provarci con'],
    [2, 'crush|mi interessa (?:un|una|lui|lei)|mi attrae|ci provo|conosciut[oa] (?:in palestra|al lavoro|a lavoro|a una festa|su)|(?:su|in) (?:tinder|bumble|hinge)|match|come (?:la|lo) approccio|approcciar\\w*'],
    [3, "(?:have|got) a (?:huge |big |massive )?crush|crush on|i (?:really )?like (?:this|a|someone|somebody) ?(?:guy|girl|person|coworker|colleague|friend)?|ask (?:him|her|them) out|asking (?:him|her|them) out|make the first move|first move|first message|slide into|confess my feelings|tell (?:him|her|them) (?:that )?i like|i'm into (?:this|a|someone|him|her)|into (?:this|a) (?:guy|girl)|matched (?:with|on)|on (?:tinder|hinge|bumble)"],
    [1.5, 'crush|flirt\\w*|asked out|interested in (?:him|her|them|someone|this)']
  ],
  new_relationship: [
    [3, 'met (?:on|through) (?:tinder|hinge|bumble|an app|the app|a dating)|met (?:\w+ )?(?:weeks|a week|a month) ago|conosciut[oa] (?:su|da) (?:\\w+ )?(?:settimane|giorni)|how often should i (?:text|call|see)|ogni quanto (?:scriverl\\w*|sentirl\\w*|vederl\\w*)'],
    [3, '(?:iniziato|cominciato) a (?:vederci|uscire|frequentarci|sentirci)|started (?:seeing|dating|talking to)'],
    [3, 'ci (?:stiamo )?frequent\\w*|frequentazione|ci sentiamo da (?:poco|qualche|un paio|due|tre|un mese|\\d)|ci vediamo da (?:poco|qualche|un paio|due|tre|un mese|\\d)|usciamo (?:insieme )?da (?:poco|qualche|un paio|due|tre|un mese|\\d)|cosa siamo|che cosa siamo|non so cosa siamo|siamo (?:solo )?all\'inizio|all\'inizio|conosciuti da poco|ci conosciamo da poco|situationship|esclusiv\\w*|primi appuntamenti|(?:primo|secondo|terzo|quarto) appuntamento'],
    [2, 'appuntament\\w*|non voglio correre|correre troppo|andare piano|troppo presto|definire (?:la cosa|il rapporto|cosa siamo)|che cos\'e questa cosa|etichett\\w*'],
    [3, "we've been (?:seeing each other|dating|talking)|been (?:seeing|dating) (?:a|this|someone)|talking stage|what are we|situationship|define the relationship|\\bdtr\\b|(?:first|second|third|fourth|few|couple of|couple) dates?|new relationship|early days|just started (?:dating|seeing)|moving too fast|take (?:it|things) slow|exclusive|label (?:it|this|things)"],
    [1.5, 'dating|date|seeing each other|weeks? (?:of dating|in)']
  ],
  commitment_future: [
    [3, '(?:vorrei|voglio|volere|want|wants) (?:dei |un |a )?(?:figli|figlio|kids|baby|children)'], [3, 'convivenza|vivere insieme|living together (?:next|soon)|moving in|move in with'],
    [3, 'andare a (?:convivere|vivere insieme)|convivere|sposar\\w*|matrimonio|avere (?:un )?figli|fare (?:un )?figli|un bambino|mettere su famiglia|futuro insieme|il nostro futuro|non si (?:vuole )?impegn\\w*|non vuole impegnarsi|paura di impegnarsi|impegnarsi|impegno|anello|proposta di matrimonio|dove (?:sta andando|stiamo andando|va) (?:la relazione|questa storia|la nostra storia)|fare un passo avanti|passo successivo|progetti (?:insieme|per il futuro|seri)'],
    [1.5, 'futuro|figli|serio|seria|stiamo insieme da (?:anni|\\d+ anni|tanto)'],
    [3, "move in together|moving in together|get married|getting married|marry (?:me|him|her|them)|marriage|propose|proposal|engage\\w*|ring|(?<!\\bmy )kids|(?<!\\bmy )children|have a baby|start a family|future together|our future|won't commit|(?:afraid|scared) of commitment|commitment\\w*|commit|where (?:this|we're|things are|it's) (?:is )?going|settle down|next step|take the next step"],
    [1.5, 'future|serious|long[- ]term|years together']
  ],
  cohabitation: [
    [3, 'whose turn|a chi tocca|thermostat|termostato|the heating|il riscaldamento|groceries|fare la spesa|to cook|cooks?|cucinare'],
    [3, "dirty dishes|in the sink|never cleans|doesn't clean|non pulisce|pulisce mai|non lava mai|lavastoviglie"],
    [3, 'faccende|pulizie|lavare i piatti|piatti|lavatrice|bucato|casa (?:sporca|in disordine)|disordine|spazzatura|immondizia|chi cucina|lavori di casa|non fa (?:mai )?niente in casa|lascia (?:tutto|le sue cose|i calzini|i vestiti) in giro|in giro per casa|(?:da quando )?(?:conviviamo|viviamo insieme)'], [2, 'coinquilin\\w*'],
    [2, 'casa|bagno|cucina|divano|calzini|spazi|il mio spazio|abitudini|russa|tavoletta|condividiamo (?:la casa|l\'appartamento)'],
    [3, "chores|housework|(?:the|do the|doing the|wash the) dishes|laundry|(?:the|a) mess\\b|messy|clean(?:ing)? up after|tidy|trash|garbage|(?:since we|now that we) (?:moved in|live together)|we live together|living together|leaves (?:his|her|their) (?:stuff|things|clothes|socks)|toilet seat|household"],
    [2, 'roommates?|flatmates?'], [1.5, 'apartment|flat|house|kitchen|bathroom|cooking|clean\\w*|our place|at home']
  ],
  money: [
    [3, 'guadagn\\w*|dividere (?:tutto )?a meta|(?:earns|makes) (?:more|double|less|twice)|pay(?:s)? me back|lend (?:him|her|them)|split (?:everything|it) (?:50/50|in half)|50/50'],
    [3, 'soldi|denaro|prestit\\w*|(?:gli|le) ho prestato|mi deve (?:dei soldi|\\d+|ancora)|debit[oi]|dividere (?:le spese|il conto|l\'affitto)|alla romana|conto (?:in comune|cointestato)|stipendio'], [3, 'spende troppo|spendaccion\\w*|paga sempre (?:io|lui|lei)|pago sempre io|non paga mai|bollette|affitto|mutuo|risparmi\\w*|\\d+ ?(?:euro|€)|€'],
    [1.5, 'spese|spesa|pagare|paga|pago|conto|costa|costo|budget|carta di credito|euro'],
    [3, "lent (?:him|her|them)|owes me"], [3, "money|loan(?:ed)?|borrow\\w*|owes me|debt|split (?:the )?(?:bill|bills|rent|costs)|splitting (?:the )?(?:bill|bills)|rent|bills|salary|paycheck|spends too much|savings|joint account|credit card|\\$ ?\\d+|\\d+ (?:dollars|bucks|pounds)"],
    [1.5, 'pay(?! attention)\\w*|paid|expensive|afford|cash|budget|financ\\w*|cost\\w*']
  ],
  family_boundaries: [
    [3, '(?:sua|suo) (?:sorella|fratello|zia|zio|nonna|nonno)|(?:his|her) (?:sister|brother|aunt|grandma) (?:always|keeps|criticizes|comments)'],
    [3, 'suocer\\w*|(?:sua|tua) madre|(?:sua|tua) mamma|(?:suo|tuo) padre|(?:suo|tuo) papa|(?:sua|tua) famiglia|la famiglia (?:di lui|di lei|del mio|della mia|sua)|i suoi (?:genitori|parenti)|(?:i genitori|la madre|la mamma|il padre) (?:del mio|della mia|di lui|di lei)|cognat\\w*|mammone|mammona|si intromett\\w*|intromission\\w*|si impiccia|invadent\\w*'],
    [1.5, 'i suoi\\b|parenti|confini|pranzo della domenica|ogni domenica|natale da'],
    [3, "(?:mother|father|sister|brother|parents)[- ]in[- ]laws?|in[- ]laws?|(?:his|her|their|my (?:husband|wife|boyfriend|girlfriend|partner|fiance)'s) (?:mom|mum|mother|dad|father|parents|family|sister|brother)|meddl\\w*|interfer\\w*|overbearing|butt(?:s|ing)? in|mama's boy|intrusive"],
    [1.5, 'boundar\\w*|holidays with|sunday lunch|relatives']
  ],
  parent_child: [
    [3, 'mia madre|mia mamma|mio padre|mio papa|i miei genitori|mio figlio|mia figlia|i miei figli|mio fratello|mia sorella|mia nonna|mio nonno|mio patrigno|mia matrigna'],
    [1.5, 'i miei\\b|genitor\\w*|adolescente|figli[oa]|papa|mamma|fratello|sorella'],
    [3, "my (?:mom|mum|mummy|mother|dad|father|parents|son|daughter|kid|kids|child|children|teen|teenager|stepmom|stepdad|stepmother|stepfather|brother|sister|grandma|grandmother|grandpa)"],
    [1.5, 'mom|mum|dad|parent\\w*|teenage\\w*|son|daughter|sibling']
  ],
  friendship_rift: [
    [3, 'amicizia|(?:la mia|il mio|una mia|un mio|mia|mio) (?:migliore )?amic[oa]|migliore amic[oa]|amic[oa] del cuore|i miei amici|le mie amiche|(?:un|una) (?:mia |mio )?amic[oa]|ci siamo allontanat\\w*|mi hanno esclus\\w*|mi ha esclus\\w*|non mi invita(?:no)? piu|la compagnia|il gruppo'],
    [1.5, 'amic\\w*|gruppo|compagnia'],
    [3, "(?:my )?best friend|\\bbff\\b|bestie|friendship|(?:my|a|an old|our|close) friend\\b|my friends|friend group|group chat|left me out|excluded me|falling out|fell out|drifted apart|(?:she|he|they) (?:stopped inviting|doesn't invite)"],
    [1.5, 'friends?|mate|buddy|pal']
  ],
  work_conflict: [
    [3, '(?:il mio|la mia|mio|mia) cap[oa]|cap[oa]\\b|collegh\\w*|collega|datore di lavoro|responsabile|(?:il mio|la mia) manager|risorse umane|mobbing|in ufficio|al lavoro|a lavoro|sul lavoro|riunione|cliente|clienti|straordinari|promozione|aumento'],
    [1.5, 'lavoro|ufficio|progetto|scadenza|team|azienda|mail|capoufficio|dipendent\\w*'],
    [3, "(?:my )?boss|(?:my|our|a) manager|co-?workers?|colleagues?|(?:at|from) work|(?:the|my) office|meeting|clients?|customers?|supervisor|teammate|employer|\\bhr\\b|performance review|promotion|raise"],
    [1.5, 'work|job|project|deadline|team|company|email']
  ],
  asking_need: [
    [3, "i need (?:my|him|her|them|you) (?:partner |boyfriend |girlfriend |husband |wife )?to|ho bisogno che|vorrei che (?:lui|lei|mi)|i'd like (?:him|her|them|my \\w+) to|how do i bring (?:it|this) up"],
    [3, `chieder(?:gli|le|e)(?! scusa)(?! di uscire) (?:un favore|una cosa|qualcosa|aiuto|di|se|piu)|vorrei chieder\\w*|come (?:glielo|gliela|gli|le) chiedo|come chiedere|un favore|ho bisogno (?:di|che)|mi servirebbe|vorrei che|vorrei (?:piu|avere)|esprimere (?:un bisogno|i miei bisogni|quello che)|dire che ho bisogno|mi piacerebbe che`],
    [1.5, 'bisogno|chiedergli|chiederle|chiedere|favore|aiuto'],
    [3, "ask (?:him|her|them) (?:for|to|if)|asking (?:him|her|them|for)|how (?:do|can|should) i ask|i need (?:him|her|them|more|to ask|some)|a (?:big )?(?:favor|favour)|i want (?:him|her|them) to|i'd like (?:him|her|them) to|express my needs|my needs|need (?:help|support) (?:with|from)"],
    [1.5, 'ask|need|help']
  ],
  hard_feedback: [
    [3, 'come (?:dico|faccio a dire|posso dire) (?:a|al|alla|ai|allo|che)|mi sta antipatic\\w*|non (?:mi )?(?:sopporto|sopporta)|how do i say (?:no|it)|non mi piace (?:il suo|la sua|come)'],
    [3, `(?:dir|far|fargli|farle|dirgli|dirle)\\w* (?:notare|presente)|dir(?:gli|le|glielo|lo) (?:di no|no|una cosa scomoda|la verita|che non mi (?:va|piace|sta bene))|come (?:glielo|gliela) dico|non so come dir(?:glielo|gli|le)|dire di no|dire no|dirle di no|dirgli di no|feedback|devo dire (?:a|al|alla|ai|alle|allo) .{0,40}che|dir(?:gli|le) che|mi da fastidio (?:che|quando|come)|mi infastidisce|lamentar\\w*|essere onest\\w* con|una cosa scomoda|rifiutar\\w*|declinare`],
    [1.5, 'fastidio|verita|dirgli|dirle|onesta'], [1.5, 'critic\\w*'],
    [3, "tell (?:him|her|them) (?:that|something|the truth|no|how i feel about)|say no|saying no|turn (?:him|her|them|it) down|(?:need|have|want|going) to tell|feedback|point out|bring (?:it|this) up|call (?:him|her|them) out|it (?:really )?(?:bothers|annoys) me|(?:hard|difficult|awkward|uncomfortable) conversation|be honest with|constructive|without hurting"],
    [2.5, 'how (?:do|can|should) i tell'], [1.5, 'honest|bother\\w*|annoy\\w*|truth']
  ],
  support_hard_time: [
    [3, 'ansia|ansios\\w*|attacch\\w* di panico|panico|depress\\w*|lutto|(?:e|sono) mort[oa]|e venut[oa] a mancare|scomparsa (?:del|della|di)|malattia|malat[oa]|ospedale|diagnosi|tumore|cancro|chemio|esaurit\\w*|burnout|momento (?:difficile|brutto|no)|periodo (?:difficile|brutto|no|nero|duro)|sta (?:malissimo|male|passando)|licenziat\\w*|ha perso (?:il lavoro|la madre|il padre|la mamma|il papa|la nonna|il nonno|il suo|la sua)|star(?:gli|le)? vicin[oa]|come (?:posso )?(?:aiutarl[aoi]|sostenerl[aoi]|supportarl[aoi])|sostenerl[aoi]|supportarl[aoi]|non sta bene|piange|crisi'],
    [1.5, 'stress\\w*|triste|tristezza|giu di morale|giu|pesante|dura'],
    [3, "anxiety|anxious|panic attacks?|depress\\w*|grie(?:f|ving)|passed away|died|death|funeral|(?:is|got|been) sick|illness|hospital|diagnos\\w*|cancer|chemo|burn(?:ed|t)? ?out|going through (?:a lot|a hard|a tough|a rough|something)|(?:hard|tough|rough|difficult) (?:time|patch|period)|lost (?:his|her|their) (?:job|mom|dad|mother|father|grandma|grandpa)|laid off|got fired|(?:support|comfort|help) (?:him|her|them)|be there for|struggling|not okay|crying"],
    [1.5, 'stress\\w*|sad|down lately|overwhelmed|exhausted']
  ],
  neglect_attention: [
    [3, 'i come (?:last|second)|come last|neanche mi guarda|non mi guarda (?:neanche|nemmeno|piu)|always busy|sempre impegnat\\w*|al computer|on (?:his|her|their) (?:laptop|computer)'],
    [3, 'trascurat\\w*|mi trascura|non ha (?:mai )?tempo per me|non mi dedica|poche attenzioni|attenzioni|mi sento sol[oa]|mi sento invisibil\\w*|non mi considera|non mi calcola|in secondo piano|ultima (?:delle sue|ruota)|sempre (?:al telefono|sul telefono|con gli amici|a giocare|alla play|a lavoro|al lavoro)|preferisce (?:gli amici|il calcio|il lavoro|la play|stare)|non fa mai niente per me|non (?:mi )?(?:dedica|trova) (?:mai )?tempo'],
    [1.5, 'tempo per me|poco tempo|play(?:station)?|videogiochi|telefono|calcio'],
    [3, "neglect\\w*|no time for me|(?:doesn't|never|don't) make time|feel (?:invisible|alone|ignored|unimportant)|lonely|always on (?:his|her|their) (?:phone|laptop|xbox|playstation)|always (?:with|out with) (?:his|her|their) friends|video ?games|plays? games|last on (?:his|her|their) list|take[sn]? me for granted|taken for granted|doesn't notice me|put me (?:second|last)|not a priority|attention"],
    [1.5, 'priority|phone|busy all the time|time together']
  ],
  affection_closeness: [
    [3, 'holds? my hand|hold hands|holding hands|little touches|(?:la|le) mano|tenermi per mano|piccoli gesti|gesti (?:dolci|affettuosi)|contatto|touches|cuddles?'],
    [3, 'affetto|affettuos\\w*|tenerezza|coccole|abbracc\\w*|non mi bacia|baci|contatto fisico|vicinanza|intimita|non facciamo piu l\'amore|fare l\'amore|passione|non mi desidera|desiderio|non mi (?:dice|ha detto) (?:piu )?(?:ti amo|ti voglio bene)|carezze|non mi tocca|dolcezza|a letto'],
    [1.5, 'ti amo|romantic\\w*|dolce|freddo a letto|bacio|tocca'],
    [3, "affection\\w*|cuddl\\w*|hugs?|kiss\\w*|(?:doesn't|won't|never) touch|physical (?:touch|contact|intimacy)|intimacy|intimate|closeness|the spark|passion|sex life|desire|(?:doesn't|never) say (?:i love you|it back)|romance|in bed"],
    [1.5, 'i love you|romantic|touch|sweet']
  ],
  disagreement_decision: [
    [2.5, "(?:io|i) (?:voglio|vorrei|want to|would like to) .{0,40}(?:e|and|but|mentre|while) (?:lui|lei|he|she|they)\\b(?! (?:non|doesn't|don't))|andare a vivere (?:in|a) (?:campagna|citta|\\w+)|move to the (?:city|country|countryside|suburbs)"],
    [3, '(?:lui|lei) vuole .{0,40}(?:io|mentre io) (?:\\w+ )?(?:vorrei|voglio|preferirei|preferisco)|(?:which|what) (?:city|country|school|house|place)|where to move|arguing about (?:which|where|whether|what)|litig\\w* (?:su|per) (?:dove|quale|se)'],
    [3, 'vacanz[ae]|dove andare|decider\\w*|decisione|scelta|scegliere|idee diverse|non siamo d\'?accordo|non (?:ci )?troviamo d\'?accordo|(?:lui|lei) vuole .{0,40} (?:io|mentre io) (?:vorrei|voglio|preferirei)|io (?:vorrei|voglio) .{0,40} (?:lui|lei) (?:vuole|preferisce)|trasferir\\w*|cambiare citta|comprare (?:casa|una macchina|un\'auto)|prendere un (?:cane|gatto)|compromesso'],
    [1.5, 'piani|programmi|weekend|natale|capodanno|d\'accordo|viaggio|estate'],
    [3, "vacation|holiday(?! with)|(?:a|the|our) trip|where to (?:go|live|spend)|decide\\w*|decision|choice|choose|disagree\\w*|(?:don't|can't|never) agree|(?:he|she|they) wants? .{0,40} (?:i|while i) (?:want|prefer|would)|i want .{0,40} (?:he|she|they) wants?|relocat\\w*|move to (?:a|another|\\w+ city)|buy a (?:house|car)|get a (?:dog|cat)|compromise"], [1.5, "new year's|christmas|thanksgiving"],
    [1.5, 'plans|weekend|summer|agree']
  ],
  reconnect: [
    [3, "(?:have not|haven't|not|never) (?:talked|spoken|seen each other) (?:in|for) (?:\\d+|two|three|a few|many) (?:years|months)|non ci (?:parliamo|sentiamo|vediamo) da (?:\\d+|due|tre|tanti|parecchi) (?:anni|mesi)|say hi (?:after|again)"],
    [3, `dopo (?:tanto tempo|molto tempo|tutto questo tempo|anni|mesi|una vita|secoli)(?! (?:di|insieme))|non ci (?:sentiamo|vediamo|parliamo) da ${TIME_LONG}|non (?:lo|la|li|le) (?:sento|vedo) da ${TIME_LONG}|ricontatt\\w*|riallacciar\\w*|riavvicinar\\w*|farmi (?:ri)?sentire|risentirci|rifarmi viv[oa]|ci siamo pers[ie] di vista|pers[oi] di vista|tornare in contatto|riprendere i contatti|vecchi[oa] amic[oa]`],
    [3, `non (?:ci )?(?:sento|sentiamo|vedo|vediamo|parlo|parliamo) .{0,40}da ${TIME_LONG}`],
    [1.5, `da ${TIME_LONG}|di nuovo|riprendere`],
    [3, "after (?:so long|all these years|all this time|years|months|a long time)|haven't (?:talked|spoken|seen (?:each other|him|her|them)|heard from (?:him|her|them)) (?:to (?:him|her|them) )?(?:in|for) (?:years|months|ages|a long time|a year)|reconnect\\w*|reach out (?:again|after)|get back in touch|back in touch|lost touch|out of the blue|old friend|rekindle"],
    [3, "haven't (?:talked|spoken|seen|heard from)(?: to| with)? .{0,40}(?:in|for) (?:years|months|ages|a long time|a year|forever)"],
    [1.5, 'years|months|ages|long time']
  ]
};

const NEG_WORDS = new Set(['non', 'not', 'no', 'never', 'mai', 'nessun', 'nessuna', 'nessuno', "don't", "doesn't", "isn't", "wasn't", "didn't", "aren't", "i'm not", 'nemmeno', 'neanche', 'senza', 'without']);

function splitTop(src) {
  const out = []; let depth = 0; let cur = ''; let cls = false;
  for (let i = 0; i < src.length; i++) {
    const c = src[i];
    if (c === '\\') { cur += c + src[++i]; continue; }
    if (cls) { if (c === ']') cls = false; cur += c; continue; }
    if (c === '[') cls = true;
    else if (c === '(') depth++;
    else if (c === ')') depth--;
    else if (c === '|' && depth === 0) { out.push(cur); cur = ''; continue; }
    cur += c;
  }
  out.push(cur);
  return out;
}

function compile(src) {
  return new RegExp(`(?:^|[^\\p{L}\\p{N}'])(${src})(?=$|[^\\p{L}\\p{N}])`, 'gu');
}

const COMPILED = [];
for (const [sit, list] of Object.entries(LEX)) {
  for (const [w, src] of list) {
    // split alternatives into negatable (!) and plain groups
    const alts = splitTop(src);
    const neg = alts.filter(a => a.startsWith('!')).map(a => a.slice(1));
    const plain = alts.filter(a => !a.startsWith('!'));
    if (plain.length) COMPILED.push({ sit, w, re: compile(plain.join('|')), neg: false });
    if (neg.length) COMPILED.push({ sit, w, re: compile(neg.join('|')), neg: true });
  }
}

function negated(s, index) {
  const before = s.slice(Math.max(0, index - 24), index).split(/[\s,.;:!?]+/).filter(Boolean).slice(-3);
  // "sono geloso" after "non": "non sono geloso" -> words [non, sono]
  return before.some(w => NEG_WORDS.has(w)) && !/\b(?:ma|but|però|pero)\b/.test(before.join(' '));
}

const TENSE = /!{2,}|\b(?:litig|urla|incazz|arrabbiat|furios|fight|yell|angry|furious|pissed|scream)\w*/;

/**
 * Classifies a free-text situation.
 * @returns {{situation, confidence, lowConfidence, scores, relation}}
 */
export function detectSituation(text, lang = 'it') {
  const s = normalize(text);
  const scores = Object.fromEntries(SITUATIONS.map(x => [x, 0]));
  for (const p of COMPILED) {
    p.re.lastIndex = 0;
    let m; let hit = false;
    while ((m = p.re.exec(s))) {
      const start = m.index + m[0].length - m[1].length;
      if (p.neg && negated(s, start)) continue;
      hit = true; break;
    }
    if (hit) scores[p.sit] += p.w;
  }
  // contextual nudges
  const rel = detectRelation(s, true);
  if (rel === 'work') scores.work_conflict += 1;
  if (rel === 'ex') scores.ex_back += 1;
  if (/\b(?:ex)\b/.test(s) && /\b(?:sua|suo|his|her|their)\s+ex\b/.test(s)) scores.ex_back -= 2;
  if (scores.betrayal >= 3 && scores.jealousy_control > 0) scores.jealousy_control -= 1;
  // long gaps are reconnection, short gaps are silence
  if (new RegExp(`\\b${TIME_LONG}\\b|\\b(?:years|months|ages)\\b`).test(s) && scores.reconnect > 0) scores.silence_ghosting -= 1.5;

  // Tiers: specific topics > frames (asking / feedback) > who-based > generic dynamics.
  // A clear cue from a higher tier damps the lower tiers.
  let higher = 0;
  for (const tier of TIERS) {
    const tierMax = Math.max(...tier.map(x => scores[x]));
    if (higher >= 3) for (const x of tier) scores[x] *= 0.6;
    higher = Math.max(higher, tierMax);
  }

  const ranked = SITUATIONS.slice().sort((a, b) => (scores[b] - scores[a]) || (RANK[a] - RANK[b]));
  const top = ranked[0]; const s1 = scores[top]; const s2 = Math.max(0, scores[ranked[1]]);
  let confidence = s1 <= 0 ? 0 : Math.min(1, s1 / 4) * (0.5 + 0.5 * (s1 - s2) / s1);
  confidence = Math.round(confidence * 100) / 100;
  const lowConfidence = s1 < 2 || confidence < 0.3;
  let situation = top;
  if (s1 < 1.5) situation = TENSE.test(s) ? 'fight' : 'asking_need';
  const relation = rel || RELATION_FROM_SITUATION[situation] || 'unknown';
  return { situation, confidence, lowConfidence, scores, relation };
}

// ---------------------------------------------------------------------------
// Relation
// ---------------------------------------------------------------------------
const RELATION_FROM_SITUATION = {
  ex_back: 'ex', first_move: 'crush', new_relationship: 'crush', work_conflict: 'work',
  friendship_rift: 'friend', parent_child: 'family', family_boundaries: 'partner',
  cohabitation: 'partner', commitment_future: 'partner', affection_closeness: 'partner',
  jealousy_control: 'partner', betrayal: 'partner', breakup: 'partner'
};

const REL_LEX = [
  ['ex', 4, /\b(?:(?:la mia|il mio|mia|mio) ex|l'ex|all'ex|my ex|ex[- ]?(?:boyfriend|girlfriend|husband|wife|partner|ragazz[oa]|fidanzat[oa]|marito|moglie))\b/],
  ['work', 3, /\b(?:cap[oa]|collegh\w*|collega|cliente|responsabile|datore di lavoro|boss|manager|co-?workers?|colleagues?|clients?|supervisor|teammate)\b/],
  ['family', 3, /\b(?:mia madre|mia mamma|mio padre|mio papa|i miei genitori|mio figlio|mia figlia|mio fratello|mia sorella|suocer\w*|cognat\w*|mia nonna|mio nonno|my (?:mom|mother|dad|father|parents|son|daughter|kid|brother|sister|grandma|grandpa)|(?:mother|father|sister|brother)[- ]in[- ]law|in-laws)\b/],
  ['friend', 2.5, /\b(?:amic[oaie]|amicizia|friends?|bff|bestie|best friend|buddy)\b/],
  ['partner', 2.5, /\b(?:(?:il mio|la mia|mio|mia) (?:ragazz[oa]|fidanzat[oa]|compagn[oa]|partner)|fidanzat[oa]|marito|moglie|convivente|boyfriend|girlfriend|husband|wife|partner|fiance\w*|spouse|hubby|stiamo insieme|we've been together|been together for)\b/],
  ['crush', 2, /\b(?:cotta|crush|mi piace (?:un|una|lui|lei)|un ragazzo che|una ragazza che|un tipo|una tipa|ci frequentiamo|ci sentiamo da poco|frequentazione|appuntament\w*|this (?:guy|girl)|a (?:guy|girl) i|someone i (?:like|met)|dating|first date|tinder|hinge|bumble|talking stage|situationship)\b/]
];

export function detectRelation(text, normalized = false) {
  const s = normalized ? text : normalize(text);
  let best = ''; let bw = 0;
  for (const [rel, w, re] of REL_LEX) {
    if (re.test(s) && w > bw) { best = rel; bw = w; }
  }
  // "il mio ragazzo e la sua ex" -> partner (the ex is a third party)
  if (best === 'ex' && /\b(?:sua|suo|his|her|their) ex\b/.test(s) && !/\b(?:mia|mio|my) ex\b/.test(s)) best = 'partner';
  // in-laws usually come up while talking to the partner
  if (best === 'family' && /\b(?:suocer\w*|cognat\w*|in-laws?|[a-z]+-in-law)\b/.test(s) &&
    /\b(?:ragazz[oa]|fidanzat[oa]|marito|moglie|compagn[oa]|boyfriend|girlfriend|husband|wife|partner)\b/.test(s)) best = 'partner';
  return best;
}

// ---------------------------------------------------------------------------
// Sign detection
// ---------------------------------------------------------------------------
// Names that are also common words / people's names need zodiac context.
const AMBIGUOUS = new Set(['cancro', 'vergine', 'bilancia', 'pesci', 'gemelli', 'acquario', 'toro', 'leone', 'leo', 'cancer', 'libra']);
const ALIASES = {};
for (const id of SIGN_IDS) {
  ALIASES[SIGN_NAMES.it[id].toLowerCase()] = id;
  ALIASES[SIGN_NAMES.en[id].toLowerCase()] = id;
}
Object.assign(ALIASES, { leos: 'leo', cancers: 'cancer', libras: 'libra', scorpios: 'scorpio', virgos: 'virgo', geminis: 'gemini', tauruses: 'taurus', capricorns: 'capricorn', aquariuses: 'aquarius', arians: 'aries', sagittarians: 'sagittarius', sagittari: 'sagittarius', capricorni: 'capricorn', scorpioni: 'scorpio', arieti: 'aries', leoni: 'leo', gemello: 'gemini', cancri: 'cancer' });

const NAME_RE = new RegExp(`(?:^|[^\\p{L}])(${Object.keys(ALIASES).sort((a, b) => b.length - a.length).join('|')})(?=$|[^\\p{L}])`, 'giu');
const CONTEXT_WORDS = /\b(?:segno|segni|zodiaco|zodiacale|ascendente|oroscopo|astrolog\w*|sign|signs|zodiac|horoscope|rising|ascendant|astrology|star sign|sun sign|moon sign)\b/;
// immediately before the sign name
const PRE_IT = /(?:\b(?:e|sei|era|siamo|sono|segno|ascendente|tipico|tipica|classico|classica|da buon|da vera|da vero|da buona)(?:\s+(?:un|una|uno|del|della|dei|dello|di))?\s*)$/;
const PRE_EN = /(?:\b(?:is a|is an|a|an|typical|classic|such a|as a|fellow|total|dating a|with a|'s a|'re a|'m a|am a|are|being a)\s*)$/;
// immediately after the sign name
const POST_CTX = /^\s*(?:man|woman|guy|girl|men|women|guys|girls|traits|sign|season|rising|ascendente|tipico|tipica|puro|pura|doc|energy)\b/;
const CANCER_DISEASE = /(?:\b(?:has|had|with|got|of|beat|beating|fighting|il|un|del|di|contro|dal|al)\s*)$/;
const SELF_PRE = /(?:\b(?:io sono|sono|i'm|i am|myself|as a|anch'io|anche io|me)\b(?:\s+(?:un|una|uno|del|della|dei|dello|a|an))?\s*)$/;
const SELF_CTX = /\b(?:(?:il mio|mio) segno|my sign|my (?:sun|zodiac)(?: sign)?)\b(?:\s+(?:e|is))?\s*$/;
const IT_WORDS = new Set(['cancro', 'vergine', 'bilancia', 'pesci', 'gemelli', 'acquario', 'toro', 'leone', 'leoni', 'gemello', 'cancri']);

/** Finds signs in free text. Returns { other, self } canonical ids ('' when absent). */
export function detectSigns(text) {
  const raw = String(text || '');
  const s = normalize(raw);
  const plain = raw.normalize('NFD').replace(/[̀-ͯ]/g, '');
  let other = ''; let self = '';
  NAME_RE.lastIndex = 0;
  let m;
  while ((m = NAME_RE.exec(s))) {
    const word = m[1].toLowerCase();
    const id = ALIASES[word];
    const start = m.index + m[0].length - m[1].length;
    const before = s.slice(Math.max(0, start - 40), start);
    const after = s.slice(start + word.length, start + word.length + 30);
    const orig = plain.slice(start, start + word.length);
    const capital = orig && orig[0] === orig[0].toUpperCase() && orig[0] !== orig[0].toLowerCase();
    const window = s.slice(Math.max(0, start - 50), start + word.length + 50);
    const ctx = CONTEXT_WORDS.test(window) || POST_CTX.test(after);
    if (AMBIGUOUS.has(word)) {
      if ((word === 'cancer' || word === 'cancro') && CANCER_DISEASE.test(before) && !CONTEXT_WORDS.test(window)) continue;
      const pre = IT_WORDS.has(word) ? PRE_IT.test(before) : PRE_EN.test(before) || (word !== 'leo' && /\b(?:is|are)\s*$/.test(before));
      const plural = /^s\b/.test(after);
      const relBefore = /\b(?:ragazz[oa]|fidanzat[oa]|marito|moglie|compagn[oa]|partner|amic[oa]|amiche|amici|mamma|madre|padre|pap[aà]|figli[oa]|sorella|fratello|suocer[oa]|cognat[oa]|capo|collega|cliente|ex|crush|boyfriend|girlfriend|husband|wife|friend|mom|mum|dad|mother|father|sister|brother|boss|coworker|colleague|son|daughter)\s+$/.test(before);
      if (capital && relBefore && word !== "leo") { /* "la mia ragazza Leone", "my boyfriend Leo" */ }
      else if (!(ctx || pre || (word === 'leo' && plural) || (capital && IT_WORDS.has(word) && /\b(?:del|della|dei|dello)\s+$/.test(before)))) continue;
    }
    const isSelf = SELF_PRE.test(before.slice(-22)) && !/\b(?:lui|lei|he|she|they|e)\s+(?:\w+\s+)?$/.test(before.slice(-14)) || SELF_CTX.test(before);
    if (isSelf) { if (!self) self = id; }
    else if (!other) other = id;
    if (other && self) break;
  }
  return { other, self };
}

/** The other person's sign mentioned in the text (canonical id or ''). */
export function detectSign(text, lang = 'it') { // eslint-disable-line no-unused-vars
  return detectSigns(text).other;
}

/** Normalises a sign given as id or IT/EN name (any case) to its id, or ''. */
export function toSignId(value) {
  if (typeof value !== 'string') return '';
  const v = normalize(value);
  if (!v) return '';
  if (SIGN_IDS.includes(v)) return v;
  if (ALIASES[v]) return ALIASES[v];
  for (const w of v.split(/[^a-z]+/)) if (SIGN_IDS.includes(w)) return w;
  for (const w of v.split(/[^a-z]+/)) if (ALIASES[w] && !['gemello', 'pesce'].includes(w)) return ALIASES[w];
  return '';
}

/** Full detection: situation + relation + signs. */
export function detect(text, lang = 'it') {
  const d = detectSituation(text, lang);
  const signs = detectSigns(text);
  return { ...d, sign: signs.other, selfSign: signs.self };
}
