// GENERATED by aura-engine/sync.mjs: do not edit here, edit /home/claude/aura-engine and re-run sync.
// Aura engine — offline answers from the sign content bank (IT / EN).
// Pure ESM, no dependencies. Sign files are loaded through an injected `loadSign(id)`
// (Node: fs read, browser: dynamic import) and cached per loader.
import { detect, toSignId, SIGN_IDS, SIGN_NAMES, SITUATIONS, normalize } from './detect.mjs';
import { pairingLine, PAIRS, ELEMENT } from './pairing.mjs';

export { detect, toSignId, SIGN_IDS, SIGN_NAMES, SITUATIONS, ELEMENT };

const FIELDS = ['whatsHappening', 'strategy', 'avoid', 'message'];
const FOLLOWUPS = ['replied', 'seen', 'unread', 'called'];

// Which profile line best sharpens the strategy for each situation.
export const INSIGHT_KEY = {
  fight: 'unlock', jealousy_control: 'trigger', silence_ghosting: 'timing', coldness_distance: 'hurt',
  ex_back: 'unlock', breakup: 'hurt', betrayal: 'hurt', apology: 'unlock', first_move: 'need',
  new_relationship: 'timing', commitment_future: 'need', cohabitation: 'trigger', money: 'trigger',
  family_boundaries: 'need', parent_child: 'hurt', friendship_rift: 'unlock', work_conflict: 'timing',
  asking_need: 'timing', hard_feedback: 'trigger', support_hard_time: 'need', neglect_attention: 'need',
  affection_closeness: 'unlock', disagreement_decision: 'timing', reconnect: 'unlock'
};

const INSIGHT_LABEL = {
  it: {
    need: s => `Di cosa ha bisogno chi è ${s}:`, trigger: s => `Cosa fa chiudere chi è ${s}:`,
    hurt: s => `Come mostra la ferita chi è ${s}:`, unlock: s => `Cosa riapre chi è ${s}:`,
    timing: () => 'Il momento giusto:'
  },
  en: {
    need: s => `What ${article(s)} ${s} needs:`, trigger: s => `What makes ${article(s)} ${s} shut down:`,
    hurt: s => `How ${article(s)} ${s} shows hurt:`, unlock: s => `What opens ${article(s)} ${s} back up:`,
    timing: () => 'Best timing:'
  }
};
function article(name) { return /^[AEIOU]/.test(name) ? 'an' : 'a'; }

export const SITUATION_LABEL = {
  it: {
    fight: 'litigio o discussione appena avvenuta', jealousy_control: 'gelosia, controllo o sospetti',
    silence_ghosting: 'silenzio, ghosting, messaggi senza risposta', coldness_distance: 'freddezza e distanza',
    ex_back: 'ex: riavvicinarsi o tornare insieme', breakup: 'chiudere una relazione o essere stati lasciati',
    betrayal: 'tradimento, bugia grave, fiducia rotta', apology: 'chiedere scusa dopo un errore',
    first_move: 'fare il primo passo con chi piace', new_relationship: 'frequentazione iniziale, ritmo e "cosa siamo"',
    commitment_future: 'impegno e futuro (convivenza, matrimonio, figli)', cohabitation: 'convivenza: casa, faccende, spazi',
    money: 'soldi, spese, prestiti', family_boundaries: 'famiglia del partner e confini',
    parent_child: 'conflitto con un genitore o un figlio', friendship_rift: 'amicizia incrinata',
    work_conflict: 'conflitto o comunicazione difficile al lavoro', asking_need: 'chiedere qualcosa o esprimere un bisogno',
    hard_feedback: 'dire una cosa scomoda, una critica o un no', support_hard_time: "stare vicino in un momento difficile",
    neglect_attention: 'sentirsi trascurati', affection_closeness: 'calo di affetto e vicinanza',
    disagreement_decision: 'idee diverse su una decisione', reconnect: 'ricontattare qualcuno dopo tanto tempo'
  },
  en: {
    fight: 'a fight or argument that just happened', jealousy_control: 'jealousy, control or suspicion',
    silence_ghosting: 'silence, ghosting, unanswered messages', coldness_distance: 'coldness and distance',
    ex_back: 'an ex: reconnecting or getting back together', breakup: 'ending a relationship or being dumped',
    betrayal: 'cheating, a serious lie, broken trust', apology: 'apologising after a mistake',
    first_move: 'making the first move with a crush', new_relationship: 'early dating, pace and "what are we"',
    commitment_future: 'commitment and the future (moving in, marriage, kids)', cohabitation: 'living together: home, chores, space',
    money: 'money, spending, loans', family_boundaries: "the partner's family and boundaries",
    parent_child: 'conflict with a parent or a child', friendship_rift: 'a strained friendship',
    work_conflict: 'conflict or tricky communication at work', asking_need: 'asking for something or voicing a need',
    hard_feedback: 'saying something uncomfortable, criticism or a no', support_hard_time: 'supporting someone through a hard time',
    neglect_attention: 'feeling neglected', affection_closeness: 'less affection and closeness',
    disagreement_decision: 'disagreeing on a decision', reconnect: 'reaching out after a long time'
  }
};

// ---------------------------------------------------------------------------
// Loading & caching
// ---------------------------------------------------------------------------
const CACHES = new WeakMap();

function validBank(b) {
  return b && typeof b === 'object' && b.situations && typeof b.situations === 'object';
}

/** Loads a bank ('none' or a sign id) through `loadSign`, cached per loader. Never throws. */
export async function getBank(id, loadSign) {
  if (typeof loadSign !== 'function' || !(id === 'none' || SIGN_IDS.includes(id))) return null;
  let cache = CACHES.get(loadSign);
  if (!cache) { cache = new Map(); CACHES.set(loadSign, cache); }
  if (!cache.has(id)) {
    const p = Promise.resolve()
      .then(() => loadSign(id))
      .then(m => (m && m.default && !m.situations ? m.default : m))
      .then(b => {
        if (!validBank(b)) throw new Error('invalid bank');
        return b;
      })
      .catch(() => { cache.delete(id); return null; }); // retry later: files may still be arriving
    cache.set(id, p);
  }
  return cache.get(id);
}

// ---------------------------------------------------------------------------
// Deterministic variant selection
// ---------------------------------------------------------------------------
export function hash(str) {
  let h = 0x811c9dc5;
  const s = String(str);
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
  return h >>> 0;
}

function seedNumber(seed) {
  if (seed === undefined || seed === null || seed === '') return 0;
  const n = Number(seed);
  if (Number.isFinite(n)) return Math.abs(Math.trunc(n)) % 1000003;
  return hash(String(seed)) % 1000003;
}

/**
 * Picks one index per slot. Slots form a mixed-radix number; each seed step adds 1 to every
 * digit (plus carry), so consecutive seeds change every slot with ≥3 variants.
 */
export function pickIndices(sizes, key, seed) {
  const n = sizes.map(x => Math.max(1, x | 0));
  let total = 1; const place = [];
  for (const x of n) { place.push(total); total *= x; }
  const K = place.reduce((a, b) => a + b, 0);
  const base = hash(key) % total;
  const c = (base + (seedNumber(seed) % total) * K) % total;
  return n.map((x, i) => Math.floor(c / place[i]) % x);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
const L = lang => (lang === 'en' ? 'en' : 'it');
const arr = v => (Array.isArray(v) ? v.filter(x => typeof x === 'string' && x.trim()) : []);

function field(bank, situation, lang, key) {
  return arr(bank && bank.situations && bank.situations[situation] && bank.situations[situation][lang] && bank.situations[situation][lang][key]);
}

const STOP = new Set('il lo la i gli le un una di a da in con su per tra fra e o ma che non si ti mi ci ne del della dei è the a an and or but to of in on for with is it you your they them that this be not'.split(' '));
function words(s) { return new Set(normalize(s).split(/[^a-z']+/).filter(w => w.length > 2 && !STOP.has(w))); }
function overlaps(a, b) {
  const A = words(a); const B = words(b);
  if (!A.size || !B.size) return false;
  let inter = 0; for (const w of B) if (A.has(w)) inter++;
  return inter / Math.min(A.size, B.size) >= 0.5 || normalize(a).includes(normalize(b));
}

function fill(template, sign, lang) {
  return sign ? template.replace(/\{sign\}/g, SIGN_NAMES[lang][sign]) : template;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Offline analysis of a situation.
 * @returns {Promise<null | {summary, whatsHappening, strategy, avoid, message, detectedSign,
 *   situation, relation, pairing, keyInsight, confidence, lowConfidence, userSign, usedBank, complete}>}
 * Fields may be '' when the bank for them is missing; `complete` tells whether all contract fields are filled.
 */
export async function analyzeSituation({ text = '', lang = 'it', knownSign = '', userSign = '', seed = 0, loadSign } = {}) {
  const lg = L(lang);
  const d = detect(text, lg);
  const sign = toSignId(knownSign) || d.sign || '';
  const mine = toSignId(userSign) || d.selfSign || '';
  const situation = d.situation;

  const [none, own] = await Promise.all([getBank('none', loadSign), sign ? getBank(sign, loadSign) : null]);
  if (!none && !own) return null;

  const pick = key => {
    const a = field(own, situation, lg, key);
    return a.length ? { list: a, from: sign } : { list: field(none, situation, lg, key), from: 'none' };
  };
  const lists = Object.fromEntries(FIELDS.map(k => [k, pick(k)]));
  const summaries = arr(none && none.summary && none.summary[situation] && none.summary[situation][lg]);
  const insightKey = INSIGHT_KEY[situation];
  const insights = arr(own && own.profile && own.profile[lg] && own.profile[lg][insightKey]);
  const pairAvailable = sign && mine && ELEMENT[sign] && ELEMENT[mine];
  const pairSize = pairAvailable ? PAIRS[`${ELEMENT[mine]}>${ELEMENT[sign]}`][lg].length : 1;

  const sizes = [summaries.length, ...FIELDS.map(k => lists[k].list.length), insights.length, pairSize];
  const idx = pickIndices(sizes, `${normalize(text)}|${sign}|${situation}|${lg}`, seed);
  // never the same index for all four main fields
  const main = idx.slice(1, 5);
  if (main.every(i => i === main[0]) && lists.message.list.length > 1) idx[4] = (idx[4] + 1) % lists.message.list.length;

  const out = {};
  out.summary = summaries.length ? summaries[idx[0]] : '';
  FIELDS.forEach((k, i) => { const l = lists[k].list; out[k] = l.length ? fill(l[idx[i + 1]], sign, lg) : ''; });

  let keyInsight = '';
  if (insights.length && sign) {
    const line = insights[idx[5]];
    if (!overlaps(out.strategy, line)) keyInsight = `${INSIGHT_LABEL[lg][insightKey](SIGN_NAMES[lg][sign])} ${lowerFirst(line, lg)}`;
  }
  if (keyInsight && out.strategy) out.strategy = `${out.strategy}\n\n${keyInsight}`;

  const pairing = pairAvailable ? pairingLine(mine, sign, lg, idx[6]) : '';
  return {
    ...out,
    detectedSign: sign,
    situation,
    relation: d.relation,
    pairing,
    keyInsight,
    confidence: d.confidence,
    lowConfidence: d.lowConfidence,
    userSign: mine,
    usedBank: lists.whatsHappening.from,
    complete: ['summary', ...FIELDS].every(k => out[k])
  };
}

function lowerFirst(s, lang) {
  // keep capitals of proper names / "I"; only lower a plain first word
  if (!s) return s;
  if (lang === 'en' && /^I\b/.test(s)) return s;
  const first = s.split(/\s/)[0];
  if (Object.values(SIGN_NAMES[lang]).some(n => first.startsWith(n))) return s;
  return s[0].toLowerCase() + s.slice(1);
}

/** Offline coach strategy after a message was sent. Returns {strategy, sign} or null. */
export async function coachStrategy({ followupType, lang = 'it', sign = '', seed = 0, text = '', loadSign } = {}) {
  const lg = L(lang);
  const type = FOLLOWUPS.includes(followupType) ? followupType : 'seen';
  const id = toSignId(sign);
  const pickFrom = b => arr(b && b.coach && b.coach[type] && b.coach[type][lg]);
  let list = []; let from = '';
  if (id) { list = pickFrom(await getBank(id, loadSign)); from = id; }
  if (!list.length) { list = pickFrom(await getBank('none', loadSign)); from = ''; }
  if (!list.length) return null;
  const [i] = pickIndices([list.length], `${type}|${id}|${normalize(text)}|${lg}`, seed);
  return { strategy: fill(list[i], from, lg), sign: from };
}

/**
 * Grounding for the AI prompt: detected situation + the sign's profile lines, as plain text.
 * Returns {text, situation, relation, sign, userSign}.
 */
export async function groundingContext({ text = '', lang = 'it', knownSign = '', userSign = '', loadSign } = {}) {
  const lg = L(lang);
  const d = detect(text, lg);
  const sign = toSignId(knownSign) || d.sign || '';
  const mine = toSignId(userSign) || d.selfSign || '';
  const bank = sign ? await getBank(sign, loadSign) : null;
  const lines = [];
  const sit = SITUATION_LABEL[lg][d.situation];
  if (lg === 'it') {
    lines.push(`Situazione rilevata automaticamente: ${sit}${d.lowConfidence ? ' (stima incerta: verifica sul testo)' : ''}.`);
    if (d.relation !== 'unknown') lines.push(`Relazione probabile: ${REL_LABEL.it[d.relation]}.`);
  } else {
    lines.push(`Automatically detected situation: ${sit}${d.lowConfidence ? ' (low-confidence guess: check against the text)' : ''}.`);
    if (d.relation !== 'unknown') lines.push(`Likely relationship: ${REL_LABEL.en[d.relation]}.`);
  }
  const prof = bank && bank.profile && bank.profile[lg];
  if (prof) {
    const name = SIGN_NAMES[lg][sign];
    lines.push(lg === 'it'
      ? `Tratti tipici di chi è ${name} da usare come lente (non come verità), scegli solo ciò che si collega ai fatti:`
      : `Typical ${name} traits to use as a lens (not as truth); use only what connects to the facts:`);
    const LBL = lg === 'it'
      ? { need: 'Bisogno', trigger: 'Cosa lo/la fa chiudere', hurt: 'Come mostra la ferita', unlock: 'Cosa lo/la riapre', timing: 'Quando parlarne' }
      : { need: 'Need', trigger: 'Shuts down when', hurt: 'Shows hurt by', unlock: 'Opens up with', timing: 'Timing' };
    for (const k of ['need', 'trigger', 'hurt', 'unlock', 'timing']) {
      const a = arr(prof[k]);
      if (a.length) lines.push(`- ${LBL[k]}: ${a.join(' / ')}`);
    }
  }
  if (mine && !sign) lines.push(lg === 'it' ? `Il segno dell'utente è ${SIGN_NAMES.it[mine]}.` : `The user's own sign is ${SIGN_NAMES.en[mine]}.`);
  if (sign && mine) {
    const p = pairingLine(mine, sign, lg, 0);
    if (p) lines.push(lg === 'it' ? `Dinamica tra gli elementi (il segno dell'utente è ${SIGN_NAMES.it[mine]}): ${p}` : `Element dynamic (the user's sign is ${SIGN_NAMES.en[mine]}): ${p}`);
  }
  return { text: lines.join('\n'), situation: d.situation, relation: d.relation, sign, userSign: mine };
}

const REL_LABEL = {
  it: { partner: 'partner', ex: 'ex', crush: 'persona che piace / frequentazione', friend: 'amicizia', family: 'famiglia', work: 'lavoro' },
  en: { partner: 'partner', ex: 'ex', crush: 'crush / someone they are dating', friend: 'friend', family: 'family', work: 'work' }
};
