// GENERATED by aura-engine/sync.mjs: do not edit here, edit /home/claude/aura-engine and re-run sync.
// Aura engine — element dynamics between the user's sign and the other person's sign.
// Keys: "<userElement>><otherElement>". Same-element pairs are symmetric; mixed pairs have
// one entry per direction, so the line is always written from the user's side.
// {o} = the other sign: IT "chi è Toro" (avoids plural agreement for Gemelli/Pesci), EN "your Taurus".
import { SIGN_NAMES } from './detect.mjs';

export const ELEMENT = {
  aries: 'fire', leo: 'fire', sagittarius: 'fire',
  taurus: 'earth', virgo: 'earth', capricorn: 'earth',
  gemini: 'air', libra: 'air', aquarius: 'air',
  cancer: 'water', scorpio: 'water', pisces: 'water'
};

export const PAIRS = {
  'fire>fire': {
    it: [
      'Due micce corte: tu e {o} vi accendete in fretta e vi spegnete in fretta. Scrivi quando la rabbia è scesa, non un minuto prima.',
      'Tra due caratteri di fuoco vince chi cede per primo senza sentirsi sconfitto: una battuta o una proposta concreta vale più di una lunga spiegazione.',
      'Con {o} non serve girarci intorno: siete entrambi diretti. Il rischio è l’escalation, quindi una frase sola, chiara, e poi lascia spazio alla risposta.'
    ],
    en: [
      'Two short fuses: you and {o} flare up fast and cool down fast. Text once the heat has dropped, not a minute before.',
      'With two fiery tempers, whoever backs down first without losing face wins: a joke or a concrete plan beats a long explanation.',
      'No need to tiptoe around {o}: you’re both direct. The risk is escalation, so send one clear line and let them answer.'
    ]
  },
  'earth>earth': {
    it: [
      'Tu e {o} ragionate per fatti: più delle parole conterà cosa fai nei prossimi giorni. Un gesto pratico chiude la questione meglio di un discorso.',
      'Due persone di terra si irrigidiscono sulle posizioni. Invece di stabilire chi ha ragione, porta la conversazione su cosa cambia in concreto da domani.',
      'Con {o} i tempi lunghi non sono freddezza: siete entrambi lenti a riaprirvi. Fissa un momento preciso per parlarne invece di aspettare che capiti.'
    ],
    en: [
      'You and {o} both run on actions: what you do over the next few days will count more than what you say. One practical gesture beats a speech.',
      'Two earth types dig their heels in. Skip who’s right and steer the conversation towards what actually changes from tomorrow.',
      'With {o}, slowness isn’t coldness: you’re both slow to reopen. Set a specific time to talk instead of waiting for it to happen.'
    ]
  },
  'air>air': {
    it: [
      'Tu e {o} parlate tanto e bene, ma rischiate di girare intorno al punto. Scrivi la cosa importante nella prima frase, il resto dopo.',
      'Tra due teste d’aria il pericolo non è il litigio, è la battuta che rimanda tutto. Una volta che avete riso, torna al punto con una domanda precisa.',
      'Con {o} funziona il ragionamento condiviso: proponi due opzioni e chiedi quale preferisce, invece di chiedere come si sente.'
    ],
    en: [
      'You and {o} both talk well and a lot, but you can circle the point forever. Put the important thing in the first line, the rest after.',
      'With two air types the danger isn’t the fight, it’s the joke that postpones everything. Laugh, then come back with one precise question.',
      'Shared reasoning works with {o}: offer two options and ask which one they’d pick, rather than asking how they feel.'
    ]
  },
  'water>water': {
    it: [
      'Tu e {o} sentite tutto, anche quello che non viene detto. Nomina l’emozione per primo tu, senza aspettare che l’altra parte indovini.',
      'Tra due persone d’acqua il silenzio diventa presto un’offesa. Un messaggio breve e caldo, anche solo per dire che ci sei, sblocca più di una spiegazione.',
      'Con {o} rischiate di chiudervi entrambi a riccio. Qualcuno deve fare il primo passo morbido: fallo tu, senza contare chi ha ceduto.'
    ],
    en: [
      'You and {o} pick up on everything, even what’s left unsaid. Name the feeling first instead of waiting for the other side to guess.',
      'Between two water types, silence quickly turns into hurt. A short warm text, even just to say you’re there, unlocks more than an explanation.',
      'With {o} you can both curl up and shut down. Someone has to make the first soft move: make it yourself and stop keeping score.'
    ]
  },
  'fire>earth': {
    it: [
      'Tu vai di slancio, {o} per passi sicuri: dopo il messaggio proponi qualcosa di concreto e aspetta la risposta senza incalzare.',
      'La tua urgenza, a chi è di terra, sembra pressione. Dai una scadenza larga, tipo “quando hai un attimo questa settimana”, e rispettala.',
      'Con {o} le promesse contano meno della costanza: meglio un piccolo gesto ripetuto per tre giorni che una grande dichiarazione stasera.'
    ],
    en: [
      'You move on impulse, {o} moves in steady steps: after the message, suggest something concrete and wait for the answer without pushing.',
      'Your urgency reads as pressure to an earth type. Give a loose deadline, like “whenever you get a minute this week”, and honour it.',
      'With {o}, consistency beats promises: a small gesture repeated for three days lands better than a big declaration tonight.'
    ]
  },
  'earth>fire': {
    it: [
      'Tu ci pensi su, {o} reagisce subito: se aspetti troppo lo legge come indifferenza. Manda un segnale rapido anche se il discorso vero arriva dopo.',
      'Chi è di fuoco vuole slancio, non verbali: accorcia il messaggio, mettici una proposta e lascia fuori l’elenco dei fatti.',
      'La tua calma può spegnere l’incendio di {o}, purché non sembri distacco. Mostra che ci tieni con una frase diretta, non con un ragionamento.'
    ],
    en: [
      'You think it over, {o} reacts on the spot: wait too long and it reads as not caring. Send a quick signal even if the real talk comes later.',
      'Fire signs want momentum, not meeting minutes: cut the message down, add a proposal and leave out the list of facts.',
      'Your calm can put out the fire in {o}, as long as it doesn’t look detached. Show you care with one direct line, not a lecture.'
    ]
  },
  'fire>air': {
    it: [
      'Tu e {o} vi alimentate a vicenda: leggerezza e ironia funzionano. Evita solo di trasformare il chiarimento in una gara a chi ha l’ultima parola.',
      'Chi è d’aria ha bisogno di capire prima di sentire: dopo lo sfogo, spiega in due righe perché la cosa ti ha toccato.',
      'Con {o} l’entusiasmo è contagioso: invece di discutere del problema, proponi un piano nuovo e lascia che sia il piano a riaprire il dialogo.'
    ],
    en: [
      'You and {o} feed each other: lightness and humour work. Just don’t turn clearing the air into a contest over who gets the last word.',
      'Air types need to understand before they feel: after venting, explain in two lines why it got to you.',
      'With {o}, enthusiasm is contagious: instead of debating the problem, pitch a new plan and let the plan reopen the conversation.'
    ]
  },
  'air>fire': {
    it: [
      'Tu analizzi, {o} vuole sentire che ci sei: meno ragionamenti, più presenza. Una chiamata breve vale più di un messaggio perfetto.',
      'Chi è di fuoco si annoia con i discorsi lunghi: taglia metà di quello che vorresti scrivere e tieni solo la frase che conta.',
      'Con {o} la tua ironia è un buon strumento, ma non usarla per sviare: prima riconosci il punto, poi alleggerisci.'
    ],
    en: [
      'You analyse, {o} wants to feel you’re there: less reasoning, more presence. A short call beats a perfect message.',
      'Fire signs tune out of long speeches: cut half of what you want to write and keep only the line that matters.',
      'With {o} your wit is a good tool, but don’t use it to dodge: acknowledge the point first, then lighten things up.'
    ]
  },
  'fire>water': {
    it: [
      'Tu parli forte, {o} sente forte: quella che per te è franchezza può arrivare come una ferita. Abbassa il volume, non il contenuto.',
      'Chi è d’acqua ha bisogno di tempo dopo lo scontro. Manda un messaggio caldo e breve, poi aspetta che si riavvicini senza pretendere risposte.',
      'Con {o} la tua rapidità può sembrare superficialità: prima di proporre soluzioni, chiedi come sta e ascolta la risposta fino in fondo.'
    ],
    en: [
      'You speak loud, {o} feels loud: what’s honesty to you can land as a wound. Turn down the volume, not the content.',
      'Water signs need time after a clash. Send one short, warm message, then wait for them to come closer without demanding answers.',
      'With {o}, your speed can look careless: before offering solutions, ask how they are and hear the answer all the way through.'
    ]
  },
  'water>fire': {
    it: [
      'Tu senti in profondità, {o} si accende in superficie e poi dimentica: non leggere la sfuriata come un giudizio definitivo su di te.',
      'Chi è di fuoco non capisce i silenzi: se qualcosa ti ha ferito, dillo in una frase chiara invece di aspettare che se ne accorga.',
      'Con {o} funziona la sincerità diretta più della delicatezza: di’ cosa ti serve senza giri di parole, apprezzerà la chiarezza.'
    ],
    en: [
      'You feel deeply, {o} flares on the surface and then forgets: don’t read the outburst as a final verdict on you.',
      'Fire signs don’t get silences: if something hurt, say it in one clear sentence instead of waiting for them to notice.',
      'With {o}, straight honesty works better than gentleness: say what you need without detours, they’ll appreciate the clarity.'
    ]
  },
  'earth>air': {
    it: [
      'Tu vai per fatti, {o} per parole: dopo il gesto concreto, aggiungi due righe che spieghino cosa significa per te.',
      'Chi è d’aria cambia idea parlando: non prendere la prima risposta come definitiva, lascia che ci ragioni e riprendi il discorso il giorno dopo.',
      'Con {o} la tua concretezza rassicura, ma la rigidità allontana. Proponi invece di imporre: “che ne dici se…” apre più di “dobbiamo”.'
    ],
    en: [
      'You go by actions, {o} by words: after the concrete gesture, add two lines explaining what it means to you.',
      'Air types change their mind while talking: don’t take the first answer as final, let them think it through and pick it up the next day.',
      'With {o}, your steadiness reassures, but rigidity pushes them away. Suggest instead of imposing: “what if we…” opens more than “we need to”.'
    ]
  },
  'air>earth': {
    it: [
      'Tu vai per parole, {o} per fatti: dopo il messaggio proponi qualcosa di concreto, con giorno e ora, invece di un generico “ne parliamo”.',
      'Chi è di terra diffida dei discorsi brillanti: meno spiegazioni, più coerenza tra quello che scrivi e quello che fai nei giorni dopo.',
      'Con {o} non cambiare versione a metà strada: scegli una posizione, dilla in modo semplice e mantienila anche se la risposta tarda.'
    ],
    en: [
      'You go by words, {o} by deeds: after the message, suggest something concrete with a day and time instead of a vague “let’s talk”.',
      'Earth signs distrust clever speeches: fewer explanations, more consistency between what you text and what you do in the days after.',
      'With {o}, don’t switch versions halfway: pick a position, say it simply and stick to it even if the reply is slow.'
    ]
  },
  'earth>water': {
    it: [
      'Tu sistemi le cose, {o} ha bisogno prima di sentirsi capito: la soluzione pratica arriva meglio dopo una frase che riconosce come sta.',
      'Tra terra e acqua c’è un’intesa naturale, ma la tua sobrietà può sembrare freddezza. Aggiungi un dettaglio affettuoso, anche piccolo.',
      'Con {o} la costanza rassicura: fatti sentire alla stessa ora per qualche giorno, senza grandi discorsi. La sicurezza arriva dai gesti ripetuti.'
    ],
    en: [
      'You fix things, {o} first needs to feel understood: the practical solution lands better after one line that acknowledges how they feel.',
      'Earth and water get along naturally, but your plainness can read as coldness. Add one affectionate detail, even a small one.',
      'With {o}, reliability soothes: check in at the same time for a few days, no big speeches. Safety comes from repeated gestures.'
    ]
  },
  'water>earth': {
    it: [
      'Tu senti, {o} fa: non aspettarti parole d’affetto, guarda i gesti. E se ti serve sentirtelo dire, chiedilo apertamente e con calma.',
      'Chi è di terra si irrigidisce davanti alle emozioni in piena: scrivi quando l’onda è passata, con un fatto e una richiesta precisa.',
      'Con {o} il non detto non arriva: quello che per te è ovvio va scritto, in modo semplice, senza allusioni.'
    ],
    en: [
      'You feel, {o} does: don’t expect words of affection, watch the gestures. And if you need to hear it, ask plainly and calmly.',
      'Earth signs stiffen when emotions run high: write once the wave has passed, with one fact and one specific request.',
      'With {o}, the unspoken doesn’t land: what feels obvious to you needs to be written down, plainly, with no hints.'
    ]
  },
  'air>water': {
    it: [
      'Tu ragioni, {o} sente: una spiegazione logica non basta se prima non riconosci l’emozione. Parti da “capisco che ti ha ferito”, poi il resto.',
      'Chi è d’acqua legge il tono più delle parole: rileggi il messaggio e togli ironia e battute, oggi non aiutano.',
      'Con {o} la tua leggerezza può sembrare distacco: resta sull’argomento anche quando diventa scomodo, senza cambiare discorso.'
    ],
    en: [
      'You reason, {o} feels: a logical explanation isn’t enough until you acknowledge the emotion. Start with “I get that it hurt”, then the rest.',
      'Water signs read tone more than words: reread your message and strip out the irony and jokes, they won’t help today.',
      'With {o}, your lightness can look detached: stay on the topic even when it gets uncomfortable, and don’t change the subject.'
    ]
  },
  'water>air': {
    it: [
      'Tu senti molto, {o} ha bisogno di capire: traduci l’emozione in una frase chiara, tipo “mi è pesato quando…”, invece di lasciarla intuire.',
      'Chi è d’aria si allontana davanti all’intensità: tieni il messaggio breve e leggero, e il discorso profondo fallo a voce.',
      'Con {o} lo spazio non è un rifiuto: se ti chiede tempo, concedilo e fissate insieme quando risentirvi.'
    ],
    en: [
      'You feel a lot, {o} needs to understand: turn the feeling into one clear sentence, like “it got to me when…”, instead of leaving it to be guessed.',
      'Air types back away from intensity: keep the message short and light, and save the deep talk for a call or in person.',
      'With {o}, space isn’t rejection: if they ask for time, give it and agree together on when to catch up.'
    ]
  }
};

export function otherRef(sign, lang) {
  return lang === 'en' ? `your ${SIGN_NAMES.en[sign]}` : `chi è ${SIGN_NAMES.it[sign]}`;
}

/** One pairing line (string) or '' when either sign is unknown. `index` picks the variant. */
export function pairingLine(userSign, otherSign, lang = 'it', index = 0) {
  const a = ELEMENT[userSign]; const b = ELEMENT[otherSign];
  if (!a || !b) return '';
  const L = lang === 'en' ? 'en' : 'it';
  const list = PAIRS[`${a}>${b}`][L];
  const i = ((index % list.length) + list.length) % list.length;
  return list[i].replace(/\{o\}/g, otherRef(otherSign, L));
}
